### ISSUE TITLE
Unreal Engine 4 support for Game Machine

### ISSUE THREAD

**Issue by HeadClot** [gamemachine/gamemachine#10]
Hey @gamemachine - would it be possible make an Unreal engine 4 Integration for Game Machine?

Let me know if this would be possible.

Thank you for your time,

HeadClot

**Comment by gamemachine** [comment]
It's on the list but not sure when I might get the time to get it in.  Would love to have one.

For a functional client most of the work is just creating a udp client, which right now I just don't have time for.  Once you have that though it's just sending the right protobuf messages.   

If someone gets a client of their own to that point, I'm happy to assist in showing exactly what messages to send for the connection related stuff or other features.  Lots of it's documented but it can be a bit scattered.

**Comment by HeadClot** [comment]
Hey @gamemachine - Good to know that it is on the list.
Thank you for making this awesome network stack.

That said - I could not help but notice this - 

>For the game itself we took the most challenging, complicated multiplayer game we could think of, a ?>massive pvp mmo with land/sea combat and siege warfare.

What engine are you using for this?

**Comment by gamemachine** [comment]
Using Unity.  I'm actually curious how well UE4 does at making decent
looking particle effects and stuff when there are a LOT of them.  That's
the main challenge with this kind of game. Most engines target games where
you have maybe a couple dozen players at most and small environments.

When it comes to a C/C++ client,  the thing is I spend most of my time in
java/C# now days so I'm just not up to speed on the best tools for the
job.  Most likely I'm just going to write the core network client in C  and
get that out first.  Second would be some higher level functionality in
C++.

**Comment by HeadClot** [comment]
> I'm actually curious how well UE4 does at making decent
looking particle effects and stuff when there are a LOT of them.  That's
the main challenge with this kind of game. Most engines target games where
you have maybe a couple dozen players at most and small environments.

http://martiancraft.com/blog/2014/08/an-unreal-decision/ - While this does not answer your question directly. It will answer it if you ever want to port your project over to unreal 4. That said this game is going to run on an Apple iPad.

Art wise Unreal Engine 4 is a dream come true. Same goes for code. That said I do not use code much. I use their visual scripting system called blueprints which allows me to do some stuff that I normally cannot do due to my artistic background.

Let me put this into perspective -

I am able to render about 50k objects and only then does it start to slow down. That said I am able to cull the scene using the world composition tools since it requires a pretty big scene to render 50k objects.

UE4 is very robust and very powerful in terms of tools. 

That said if GameMachine does come to Unreal 4 please include blueprint functionality within the editor. I would love to use this for my own game but I lack c++ code skills and it would make the artists job allot easier.

Would it be OK if I pulled some more experienced people in this chat to give you a better idea?

>When it comes to a C/C++ client,  the thing is I spend most of my time in
java/C# now days so I'm just not up to speed on the best tools for the
job.  Most likely I'm just going to write the core network client in C  and
get that out first.  Second would be some higher level functionality in
C++.

https://www.youtube.com/watch?v=hGBVBJUZ6Jc - C# in Unreal 4 still not out but it is going to be out by or announced at GDC 2015 from my speculation. So do not quote me on it. Which is less than a month or so away.

**Comment by gamemachine** [comment]
Ya pull in whoever you think might help.   I would love to support UE4 and
any info that might along that path is great.

Chris

On Sat, Feb 14, 2015 at 11:59 PM, Benjamin Stanley <notifications@github.com

**Comment by Allar** [comment]
Setting up a UDP socket in UE4 is relatively trivial.

That said....

Unless people want to just be passing data around and then setting up their own Unreal hooks to make that data meaningful, incorporating any networking framework into UE4 that would directly handle things like actor replication and events being fired off would be incredibly tedious without direct support from Epic.

**Comment by gamemachine** [comment]
Hi MIchael,


So I'm now thinking of a different approach here.  It would be far easier
to just emulate their network protocol and then add support for their
messaging format.  We have all the hooks in place to do that well.

We have a pipeline for custom network protocols.   We use Netty that has a
built in pipeline for supporting literally anything.   All of our internal
messaging and most data structures are protobuf but we have a system to
generate custom protobuf source to support serialization to other formats.
Like we currently have toJson/fromJson and toProto/fromProto methods.  We
can just add toUE4/fromUE4.  The pipeline then calls these on the way
in/out.

Mapping rpc's to game machine actors should be straight forward, as we
already use a routing system for this ourselves.

Still a chunk of work don't get me wrong.  But once done it should be a
very clean integration that basically looks just like the standard UE4
networking.

**Comment by HeadClot** [comment]
@gamemachine - In regards to particles this should answer your question. You might have to use some middleware from Nvidia (FLEX) however it is or is going to be publicly available very soon as part of the Nvidia's UE4 branch.

https://forums.unrealengine.com/showthread.php?53735-NVIDIA-GameWorks-Integration&p=215131&viewfull=1#post215131

Read the post from where I linked to the bottom of that page.

**Comment by Allar** [comment]
Regarding looking like UE4 networking, there is a way to be completely transparent if you create your own NetDriver implementation. I don't know anything else outside of this, but this is what Steam uses to  replace UE4's standard networking with its own steam packet wrapped setup.

**Comment by gamemachine** [comment]
Interesting.  If they actually have an official api like that it might be
easier then I thought.  Will have to take a look.

**Comment by j** [comment]
Hey guys, just resurrecting this post.  I just came across this repository.  Just noting that since this discussion has happened, versions 4.8 came out and Unreal Engine announced that it is free / open sourced.  I'm not sure if they include all networking logic or if they have some magic in the way unreal games are compiled, so this may be a useless bleep. :)

**Comment by HeadClot** [comment]
Hey @j - Thanks for the bleep on your end. I have totally forgot about this repo. :)

**Comment by PolywickStudio** [comment]
@HeadClot , I checked... 

Most of the things provided by Unreal Engine server has many/most of the feature-set provided by GameMachine.

Many of the features contained within GameMachine is to correct the deficiencies in Unity3d for it to be an applicable and usable MMO.
